# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_promote_pbf_export_format'),
        ('jobs', '0028_promote_osm_export_format'),
    ]

    operations = [
    ]
