# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_merge'),
        ('jobs', '0029_job_metadata'),
    ]

    operations = [
    ]
