# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_exportrun_user'),
    ]

    operations = [
        migrations.RunSQL('alter table export_task_results add column id serial'),
       migrations.RunSQL('alter table export_task_results drop constraint export_task_results_task_id_96daaf52_fk_export_tasks_id'),
       migrations.RunSQL('create unique index export_task_results_id on export_task_results(id)'),
       migrations.RunSQL('alter table export_task_results drop constraint export_task_results_pkey'),
       migrations.RunSQL('alter table export_task_results add primary key using index export_task_results_id'),
    ]
