# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_auto_20160226_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttaskresult',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
